# Generated by Django 4.0.5 on 2022-07-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_temp', models.FloatField(null=True)),
                ('max_temp', models.FloatField(null=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
