# Generated by Django 4.0.5 on 2022-07-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current_temp',
            field=models.FloatField(null=True),
        ),
    ]
