# Generated by Django 4.0.5 on 2022-08-01 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mon', '0003_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSensor',
            fields=[
                ('sensor_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sensor_description', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tb_m_sensor',
            },
        ),
        migrations.CreateModel(
            name='MasterThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_warning', models.FloatField()),
                ('sensor_danger', models.FloatField()),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mon.mastersensor')),
            ],
            options={
                'db_table': 'tb_m_sensor_threshold',
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mon.mastersensor')),
                ('threshold_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mon.masterthreshold')),
            ],
            options={
                'db_table': 'tb_r_sensor',
            },
        ),
        migrations.DeleteModel(
            name='event',
        ),
    ]
