# Generated by Django 4.0.5 on 2022-08-01 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mon', '0004_mastersensor_masterthreshold_temperature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mon.mastersensor')),
                ('threshold_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mon.masterthreshold')),
            ],
            options={
                'db_table': 'tb_r_sensor',
            },
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
