# Generated by Django 4.0.5 on 2022-08-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon', '0005_temperature_data_delete_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterthreshold',
            name='Sensor_ID',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
