# Generated by Django 4.0.5 on 2022-08-05 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mon', '0006_masterthreshold_sensor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterthreshold',
            name='Sensor_ID',
        ),
    ]
