# Generated by Django 4.0.5 on 2022-08-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon', '0008_masterthreshold_threshold_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature_data',
            name='status',
        ),
        migrations.AddField(
            model_name='masterthreshold',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
