# Generated by Django 4.0.5 on 2022-08-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mon', '0009_remove_temperature_data_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterthreshold',
            name='threshold_id',
        ),
    ]
