# Generated by Django 4.0.5 on 2022-08-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon', '0010_remove_masterthreshold_threshold_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterthreshold',
            old_name='description',
            new_name='threshold_description',
        ),
        migrations.AddField(
            model_name='masterthreshold',
            name='threshold_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
