# Generated by Django 4.0.5 on 2022-08-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon', '0011_rename_description_masterthreshold_threshold_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature_Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tb_temperatur',
            },
        ),
    ]
