# Generated by Django 3.1.2 on 2020-10-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rumdat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.FileField(upload_to='')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('about', models.TextField(blank=True, max_length=1000)),
                ('address', models.TextField(blank=True, max_length=235)),
                ('hobby', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
